kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build web
  image: node:16.14.0-alpine
  volumes:
  - name: node-modules
    path: /drone/src/web/node_modules
  commands:
  - rm -rf ./simple-server/src/main/resources/dist
  - cd ./simple-web
  - yarn config set registry https://registry.npm.taobao.org && yarn config set disturl https://npm.taobao.org/dist
  - yarn && yarn build
  - mv /drone/src/simple-web/dist /drone/src/simple-server/src/main/resources
  - echo "Build Web Success!"
- name: Maven Package
  image: maven:3-jdk-8
  volumes:
  - name: maven-repository
    path: /root/.m2
  commands:
  - cd ./simple-server
  - mvn -Dmaven.test.skip=true clean package
  - ls /drone/src/simple-server/target | grep -v *.jar | xargs rm -rf
  - echo "Maven Package Success!"
- name: deploy
  image: drillster/drone-rsync
  settings:
    hosts:
      - 192.168.123.232
    key:
      from_secret: private_key
    source: /drone/src/simple-server/target/
    target: /opt/app/
    include:
      - "simple-server-1.0-SNAPSHOT.jar"
    exclude:
      - "**.*"
- name: ssh
  image: appleboy/drone-ssh
  settings:
    host:
      - 192.168.123.232
    username: root
    key:
      from_secret: private_key
    port: 22
    command_timeout: 2m
    script:
      - pid=$(jps | grep simple-server | awk "{print \$1}");if [ -n "$pid" ]; then echo "Shutdown...${pid}";kill -9 $pid; fi
      - java -jar -Duser.timezone=GMT+8  /opt/app/simple-server-1.0-SNAPSHOT.jar --spring.profiles.active=test >/dev/null 2>log &
      - echo Done!
#- name: dingtalk
#  image: lddsb/drone-dingtalk-message
#  settings:
#    type: markdown
#    token:
#      from_secret: dingtalk_token
#    secret:
#      from_secret: dingtalk_secret

volumes:
  - name: maven-repository
    host:
      path: /root/.m2
  - name: node-modules
    host:
      path: /root/node_modules
