spring:
  datasource:
    url: jdbc:mysql://localhost:3306/simple_server?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: dev
    password: dev%localhost
  resources:
    static-locations: classpath:/dist
  mvc:
    static-path-pattern: /web/**
server:
  port: 8095
#mybatis配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: flag  #全局逻辑删除字段值 3.3.0开始支持，详情看下面。
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      id-type: none
  configuration:
    # 开启sql日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: src/main/com/simple/mapper/*.xml
  
logging:
  level:
    root: INFO
    com.simple.feign.WechatFeignClient: DEBUG