spring:
  datasource:
    url: jdbc:mysql://192.168.123.232:3306/simple_admin?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
  resources:
    static-locations: classpath:/html
  mvc:
    static-path-pattern: /web/**
server:
  port: 8095
#mybatis配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: flag  #全局逻辑删除字段值 3.3.0开始支持，详情看下面。
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      id-type: none
  configuration:
    # 开启sql日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: src/main/com/simple/mapper/*.xml
logging:
  config: classpath:logback-spring.xml
  
pay:
  alipay:
    private-key: 
    public-key: 
    alipay-public-key: 
    pay-gateway: https://openapi.alipaydev.com/gateway.do
    appid: 
    return-url: http://192.168.1.107:8095/api/pay-success/sync-alipay
    pay-result-page: http://192.168.1.107:8095/web/tradeDetail.html
    notyfy-url: http://xx.cn:9990/api/pay-success/alipay
    account: xxx@sandbox.com
connector:
  ak: 22
  sk: 22